/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds
 */
plugins {
    kotlin("jvm") version "1.3.41"
}

repositories {
    mavenCentral()
}

extra.apply {
    set("junitVersion", "5.5.0")
    set("assertjVersion","3.12.2")
}

dependencies {
    implementation(kotlin("stdlib-jdk8"))

    val junitVersion = project.extra.get("junitVersion")
    testImplementation("org.junit.jupiter:junit-jupiter-api:$junitVersion")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:$junitVersion")
    testImplementation("org.assertj:assertj-core:${project.extra["assertjVersion"]}")
}